#!/usr/bin/env bash

# todo. add yaml front matter include "code: true"

Top=$(git rev-parse --show-toplevel)

There=$Top/../web
Url=https://github.com/se4ai/code/tree/master
py2md() {
gawk 'BEGIN {  
         q="\""
         print ""
         First = 1      
         In = 1
  }         
  /^# /{ sub(/^#/,"")
        print "---"
        print "title: " $0
        print "layout: default"
        print "code: true"
        print "---"
        print ""
        print "Read the code on [Github]("$Url/$1")."
        print ""
      }
  /^"""</,/^>"""/ {  next } 
  /^"""/          {  In = 1 - In       
                     if (In)            
                       print "````python"
                     else          
                       if (First)   
                         First = 0   
                       else     
                         print "````"  
                     next }       
  ! First { print (In ? sprintf("%4s. ",++n) : "") $0 }       
  END     { if (In) print "````"
            }'
} 
main() {
  com=$1
  arg=$2
  file=$(basename $arg)
  stem="${file%%.*}"
  out=$There/${stem}.md
  echo "# $(basename $arg) ==> $out"
  cat $1 | $com $file  > $out
  #git add $out
}
if [ -n "$1" ]; then
  main $1
  git commit -am as
else
  for f in $There/*.py; do
    main py2md $f
  done
  #git commit -am as
  #git push
fi

