#!/usr/bin/env bash

# todo. add yaml front matter include "code: true"

Top=$(git rev-parse --show-toplevel)

There=$Top/../web
Url="https://github.com/se4ai/code/tree/master"

md2md() {
  cat $1 | gawk '
  /^# /{ sub(/^#/,"")
        print "---"
        print "title: \"" $0 "\""
        print "layout: default"
        print "---"
        next
      }
  1 '
} 
py2md() {
  url="$2"
  file="$1"
  cat $file | gawk 'BEGIN {  
         q="\""
         print ""
         First = 1      
         In = 1
  }         
  /^# /{ sub(/^#/,"")
        print "---"
        print "title: \"" $0 "\""
        print "layout: default"
        print "code: true"
        print "---"
        print ""
        print "Read the code on [Github]('$url') <font color=orange><i class=\"fab fa-github-3x\"></i></font>."
        print ""
      }
  /^"""</,/^>"""/ {  next } 
  /^"""/          {  In = 1 - In       
                     if (In)            
                       print "````python"
                     else          
                       if (First)   
                         First = 0   
                       else     
                         print "````"  
                     next }       
  ! First { print (In ? sprintf("%4s. ",++n) : "") $0 }       
  END     { if (In) print "````"
            }'
} 
main() {
  com=$2
  arg=$1
  file=$(basename $arg)
  stem="${file%%.*}"
  out=$There/${stem}.md
  rm -rf  $out
  #if [ "$1" -nt "$out" ]; then
    echo "# $(basename $arg) ==> $out"
    $com $1 $Url/$file > $out
    (cd $There; git add $out)
  #fi
}


mkdir -p $There/img

cp $Top/img/* $There/img
(cd $There; git add $There/img/*)

for f in src/*.py; do main $f py2md ; done
for f in src/*.md; do main $f md2md ; done

cd $There
git commit -am as
git push
