#!/usr/bin/env bash

Ext=auk
Lib=$HOME/opt/$Ext/awk
Bin=$HOME/opt/$Ext/bin
Doc=$HOME/opt/$Ext/doc

prep() { gawk ' {
  print gensub(/\.([^0-9])([a-zA-Z0-9_]*)/, 
               "[\"\\1\\2\"]","g",$0) }' 
}
preps() {
  Files=$(find . -name "*.$Ext")
  for i in $Files;do
     f=$(basename $i)
     l=$Lib/${f%.$Ext}.awk
     b=$Bin/${f%.$Ext}
     if [ "$i" -nt "$l" ]; then cat $i | prep > $l; fi
     if [ "$l" -nt "$b" ]; then
       echo '#!/usr/bin/env gawk -f ' > $b
       cat $l >> $b
       chmod +x $b
     fi
  done
}
mkdir -p $Lib $Bin

if [ "$1" == "0" ]; then
  rm -rf $Lib/* $Bin/* $Doc/*
  shift
fi

chmod +x *.auk
preps

if [ -z "$1" ]; then exit 0; fi

f=$(basename $1)
l=$Lib/${f%.$Ext}.awk

shift
AWKPATH="$Lib:$AWKPATH" gawk -f $l $*
