#!/bin/bash 
Root=$(git rev-parse --show-toplevel)

if [ ! -d "$HOME/.vim/bundle" ]; then 
  mkdir -p $HOME/.vim/bundle
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle
  /usr/local/bin/vim  -u "$Root/lib/dotvimrc" +PluginInstall +qall 
fi

_c0="\033[00m"     # white
_c1="\033[01;32m"  # green
_c2="\033[01;34m"  # blue
_c3="\033[31m"     # red
_c5="\033[35m"     # purple
_c6="\033[33m"     # yellow
_c7="\033[36m"     # turquoise

here() { cd $1; basename "$PWD"; }

export PROMPT_COMMAND='echo -ne "::${_c7}@${_c0}$(hostname -s):${_c6}$(git branch 2>/dev/null | grep '^*' | colrm 1 2) \033]0;$(here ../..)/$(here ..)/$(here .)\007";PS1="${_c1}$(here ../..)/$_c2$(here ..)/$_c3$(here .) ${_c6}\!>${_c0}\e[m "'

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gc="git config credential.helper 'cache --timeout=3600'"
alias get='git pull'
alias grep='grep --color=auto'
alias ls='ls -G'
alias put='gc; git commit -am saving; git push; git status'
alias vi="/usr/local/bin/vim -u $Root/lib/dotvimrc"

pathadd() {
      if  [[ ":$PATH:" != *":$1:"* ]]; then
          export PATH="${PATH:+"$PATH:"}$1"
      fi
}
pathadd $Root/bin
pathadd /usr/local/bin
